ARG VERSION
ARG ARCHES_PROJECT
ARG WEB_ROOT=/web_root
ARG STATIC_ROOT=/static_root
ARG ARCHES_DYNAMIC_IMAGE=flaxandteal_${ARCHES_PROJECT}:$VERSION
ARG ARCHES_STATIC_IMAGE=flaxandteal_${ARCHES_PROJECT}_static:$VERSION
FROM $ARCHES_STATIC_IMAGE as arches_static

FROM $ARCHES_DYNAMIC_IMAGE as arches
ARG STATIC_ROOT=/static_root

COPY --from=arches_static /usr/share/nginx/webpack-stats.json ${WEB_ROOT}/${ARCHES_PROJECT}/webpack/webpack-stats.json
COPY --from=arches_static /usr/share/nginx/frontend_configuration ${WEB_ROOT}/${ARCHES_PROJECT}/frontend_configuration
# RUN mkdir -p ${STATIC_ROOT}/CACHE
# COPY --from=arches_static /usr/share/nginx/html/static/CACHE/manifest.json ${STATIC_ROOT}/CACHE/manifest.json
COPY --from=arches_static /usr/share/nginx/html ${WEB_ROOT}/${ARCHES_PROJECT}/${ARCHES_PROJECT}/media/build

# Now that collectstatic has run and webpack output is in media/build, the bulky
# node_modules trees in arches/ and the project root are no longer needed at runtime.
USER 0
RUN rm -rf ${WEB_ROOT}/arches/node_modules \
           ${WEB_ROOT}/${ARCHES_PROJECT}/node_modules \
           /root/.cache/pip /root/.npm /tmp/* \
    && find ${WEB_ROOT} -type d -name __pycache__ -prune -exec rm -rf {} + || true
USER 1000
